### ISSUE TITLE
Tip van Berat

### ISSUE THREAD

**Issue by amirnapoletano** [Demivdm/Platform-Grote-Themas#10]
Gebruik geen wit, maar een grijzere kleur.

**Comment by Tristandemuijnck** [comment]
Dit gaat over tekst kleur ^. Wit is niet heel natuurlijk. Misschien een andere tint van wit?

**Comment by Demivdm** [comment]
![image](https://github.com/Demivdm/Platform-Grote-Themas/assets/112861166/f043620d-0f38-4345-8470-b143c86709c7)

Licht grijze kleur gekozen als alternatief voor de witte tekst.
