### ISSUE TITLE
Tip: Geef voor de dropdown goed onderscheid tussen een actieve optie en alle andere opties

### ISSUE THREAD

**Issue by Stefan-Espant** [Demivdm/Platform-Grote-Themas#12]
Zo maak je het begrijpelijk voor de gebruiker

**Comment by Demivdm** [comment]
Thanks! Goede feedback:) Ik heb het verwerkt.
![image](https://github.com/Demivdm/Platform-Grote-Themas/assets/112861166/cdd28b38-0910-4cbc-ba4d-e41e87214d8a)
