### ISSUE TITLE
tip van Top G Justus

### ISSUE THREAD

**Issue by amirnapoletano** [Demivdm/Platform-Grote-Themas#13]
Gebruik alleen maar. email adres met een link die wordt gestuurd om in te loggen, zo hoef je mider data op te slaan

**Comment by Tristandemuijnck** [comment]
Magic link toevoegen ^

**Comment by Tristandemuijnck** [comment]
Magic links toegevoegd

639e4605df80de02aa0f701bfd65f2812b75e57b
