### ISSUE TITLE
Design feedback

### ISSUE THREAD

**Issue by Maaike0904** [Demivdm/Platform-Grote-Themas#9]
Tip: Wat nou als je terug wil? Terwijl je gaat registreren. Wel veel witruimte tussen de tekst en registreerveld
Top: Rustig geheel, mooie registreer knop.

**Comment by Tristandemuijnck** [comment]
Terug gaan is opgelost d.m.v. breadcrumbs. Ook de witruimte is opgelost door het centreren van de sections
